### ISSUE TITLE
Modificar el menú de las ciudades

### ISSUE THREAD

**Issue by jamescr** [labexp/lascallesdelasmujeres#2]
Actualmente en el mapa aparecen varias ciudades de Argentina (Buenos Aires, Rosario, Resistencia), es muy probable que otras que pronto se agreguen otras ciudades de países que ya están en el mapa (por ejemplo el caso de Alajuela, Heredia, San José en Costa Rica). Entonces qué les parece modificar el menú para que incluya un submenú en cada país. El funcionamiento sería que el menú primero lista los países de los cuales hay al menos una ciudad y en el submenú se despliegan las ciudades de ese país. 

(nota: intentemos resolver este issue antes de aceptar el PR #1, para enviárselo al upstream y así de paso resolvemos el asunto de qué nombre ponerle al menú de Costa Rica GAM )

**Comment by tammypmc** [comment]
Este issue fue implementado en https://github.com/labexp/lascallesdelasmujeres/pull/9
